### ISSUE TITLE
[meta] Wishlist for smallvec 2.0

### ISSUE THREAD

**Issue by mbrubeck** [servo/rust-smallvec#183]
These are changes that weren't ready in time for 1.0 (#73).

Forward port changes from the v1 branch:

- [X] drop bincode2 support #426 

Requires newer version of Rust than current minimum (1.36):

- [x] Use const generics to change `SmallVec<[T; N]>` to `SmallVec<T, N>`. Remove the `Array` trait. (#240, Rust 1.51).
- [x] Use the `union` representation by default and remove the optional `union` feature added in #94 (Rust 1.49).
- [x] Make `SmallVec::new` a `const fn` (#263).

Depends on unstable Rust features:

- [ ] Support custom allocators (#55, rust-lang/rust#32838).
- [x] Use specialization to optimize `extend`, `insert_many`, and `from` for slices of `Copy` types. Deprecate and remove `extend_from_slice`, `insert_from_slice`, and `from_slice` (#384, rust-lang/rust#31844).
- [x] Implement the `Error` trait without requiring `std` (#355, rust-lang/rust#103765).

Breaking API changes:

- [x] Fix variance of `SmallVec<[T; N]>` over `T` (#146)?
- [x] Remove the deprecated `ExtendFromSlice` trait.
- [x] Remove unused `&self` parameter from `inline_size` method.
- [x] Deprecate the `write` feature and add a `std` feature instead (#355, #356).
- [x] Remove the non-standard `insert_many` method (#255)?

**Comment by protodeniz** [comment]
`std::io::write` will move into `core` most likely, according to https://github.com/rust-lang/rust/issues/154046. maybe it would be nice to squash that in here as well and ungate (`std`) the implementation of `Write` trait?

**Comment by alejandro-vaz** [comment]
@protodeniz agree, but it seems that it is taking a while

hopefully it stabilizes before the end of the year

**Comment by alejandro-vaz** [comment]
the wishlist is basically fully implemented, except for allocators, but given that it might be stabilizing soon that might be a better option

@TDecking has been working on it, he knows better than me

the current wishlist is our issues tab, so this is not of much use anymore

**Comment by protodeniz** [comment]
> [@protodeniz](https://github.com/protodeniz) agree, but it seems that it is taking a while
> 
> hopefully it stabilizes before the end of the year

i've been following the convo closely. it seems like the `Write` trait won't be in `core::io` sadly. on the plus side, it will be in `alloc::io`. and maybe if it aligns with this libraries goals, it could add support for `embedded_io`, which will basically use the new `core::io::Error` in the future most likely for its `core`-only `Write` and `Read` trait. at least i'm going to be using that anyway (along with `embedded_io_async`, as i see they are the most agnostic atm) :)
