### ISSUE TITLE
[meta] Wishlist for 1.0

### ISSUE THREAD

**Issue by mbrubeck** [servo/rust-smallvec#73]
This is a list of breaking changes that we would like to make before stabilizing the API for smallvec 1.0.

Increases the minimum Rust version from 1.20:

- [x] Use the `alloc` crate for `no_std` compatibility (#159, Requires Rust 1.36).
- [x] Replace `mem::uninitialized` with `MaybeUninit` (#126, Requires Rust 1.36).
- [x] Use `NonNull<T>` instead of `*mut T` (#171, Requires Rust 1.25).
- [x] Replace the `unreachable` crate with `std::hint::unreachable_unchecked` (#128, Requires Rust 1.27).

Breaking API changes:

- [x] Change `drain` method to take a `RangeBounds` argument (#142, Requires Rust 1.28).

Deprecations:

- [x] Remove deprecated `SmallVecN` type aliases.
- [x] Remove deprecated `push_all_move` method.
- [x] Remove deprecated `VecLike` trait.

Still depends on unstable Rust features. Postpone until 2.0:

- [ ] Use const generics to change `SmallVec<[T; N]>` to `SmallVec<T, N>`. Remove the `Array` trait. (rust-lang/rust#44580).
- [ ] Support custom allocators (#55, rust-lang/rust#32838).
- [ ] Use specialization to optimize `extend`, `insert_many`, and `from` for slices of `Copy` types. Deprecate and remove `extend_from_slice`, `insert_from_slice`, and `from_slice` (rust-lang/rust#31844).
- [ ] Use the `union` representation by default and remove the optional `union` feature added in #94 (rust-lang/rust#32836).

**Comment by llogiq** [comment]
Regarding specialization, I can see how the `From` implementation can work out, but wouldn't `Extend` and `insert_many` violate coherence rules?

**Comment by mbrubeck** [comment]
Specializing these would require adding an intermediate trait with a default impl and specialized impls, like libstd's [`impl Extend for Vec`](https://doc.rust-lang.org/1.28.0/src/alloc/vec.rs.html#1815-1826).

**Comment by cbarrick** [comment]
Might I suggest adding an updated `drain` to the list.

`SmallVec::drain` was implemented in #26, but does not accept a range argument like `Vec::drain`. At the time, `RangeArgument` (now `RangeBounds`) had not stabilized. `RangeBounds` is now stable since Rust 1.28.

**Comment by mbrubeck** [comment]
Many of the unstable Rust features seem unlikely to stabilize any time soon. I think we should consider making a 1.0 release in the near future (sometime this year) which would include everything that is stable now (or in the very near future), and then make a 2.0 release much later (probably 2 or more years from now) with features that stabilize later.

The following would be delayed until 2.0 or later:

* const generics
* union
* custom allocators
* specialization

The following *might* be ready in time for 1.0:

* MaybeUninit
* liballoc

It might be worth waiting until MaybeUninit is stabilized, since that fixes a potentially critical soundness issue.  Alternately we could use build-time rustc version detection to conditionally use MaybeUninit, but this would increase code complexity and we would need to live with it for potentially a long time.

**Comment by lfairy** [comment]
`MaybeUninit` and `alloc` are now stable. Do we want to update this issue?

**Comment by mbrubeck** [comment]
I posted a PR for a 1.0.0 release in #175 

I'd like to publish this as soon as possible, because lack of `MaybeUninit` in existing releases is UB waiting to happen, and is already impacting downstream projects that run MIRI tests. We can release a 2.0 version next year or whenever const generics are ready.

**Comment by llogiq** [comment]
There's a [neat trick](https://github.com/dtolnay/case-studies/tree/master/autoref-specialization) written up by @dtolnay to emulate specialization on stable. I haven't looked too deeply into how well that performs, but it's probably worth a shot trying to use it.

**Comment by matklad** [comment]
@mbrubeck thank you for putting work into this!

Seems like the issue can be closed and a new one, wishlist for 2.0, opened instead

**Comment by mbrubeck** [comment]
Filed #183 to track 2.0 progress.
